baseURL = 'https://duncan020313.github.io/blog/'
defaultContentLanguage = 'en'
title = 'Dongjae Lee Blog'
theme = 'archie'
copyright = "© Dongjae Lee"
googleAnalytics = "G-6837PZBEDR"

# Language configuration
[languages]
  [languages.en]
    title = "Dongjae's Blog"
    languageName = 'English'
    languageCode = 'en-us'
    weight = 1
    copyright = "© Dongjae Lee"


  [languages.ko]
    title = "Dongjae's Blog"
    languageName = '한국어'
    languageCode = 'ko-kr'
    weight = 2
    copyright = "© Dongjae Lee"

[pagination]
	pagerSize = 3

[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=true # use CDNs for fonts and icons for reliable loading
	mathjax = false # enable MathJax support
	katex = true # enable KaTeX support
	customCSS = ["css/custom.css"] # Custom CSS for language switcher

[[params.social]]
name = "GitHub"
icon = "simple:github"
url = "https://github.com/duncan020313"

[[params.social]]
name = "X"
icon = "simple:x"
url = "https://x.com/djlee0313"

[[params.social]]
name = "LinkedIn"
icon = "simple:linkedin"
url = "https://www.linkedin.com/in/%EB%8F%99%EC%9E%AC-%EC%9D%B4-b837a824b/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base%3BMcbpTWGORz6Qi0ptP6FRBg%3D%3D"

# English menu
[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[languages.en.menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[languages.en.menu.main]]
name = "About"
url = "/about"
weight = 3

# Korean menu
[[languages.ko.menu.main]]
name = "홈"
url = "/ko"
weight = 1

[[languages.ko.menu.main]]
name = "포스트"
url = "/ko/posts"
weight = 2

[[languages.ko.menu.main]]
name = "소개"
url = "/ko/about"
weight = 3

[params.giscus]
  repo = "duncan020313/blog"
  repo_id = "R_kgDOO_W5AQ"
  category = "Announcements"
  category_id = "DIC_kwDOO_W5Ac4CrzaI"
  mapping = "pathname"
  strict = "0"
  reactions_enabled = "1"
  emit_metadata = "0"
  input_position = "bottom"
  crossorigin="anonymous"